#ifndef __UTILITIES_H__
#define __UTILITIES_H__
#include <signal.h>

#define MAXSTRLEN           64
#define MAXNUMSAMPLES       0x200
#define BYTESPERLED         0x03
#define BYTESPERSAMPLE      (BYTESPERLED*2)

typedef enum {
    PING = 0,
    PONG = 1,
} pingpongIndex_t;

typedef enum {
    NOERROR=0,
    I2C_SUCCESS=0,
    REG_NOERROR = 0,
    DONE=1,
    I2C_WRITE_ERROR=-1,
    I2C_READ_ERROR=-2,
    I2C_WRITE_REMNZ_ERROR=-3,
    I2C_READ_REMNZ_ERROR=-4,
    READMAX30102_FIFO_ERROR=-5,
    REG_FIFO_WR_PTR_READ_ERROR = -6,
    REG_FIFO_WR_PTR_WRITE_ERROR = -7,
    REG_FIFO_RD_PTR_READ_ERROR = -8,
    REG_FIFO_RD_PTR_WRITE_ERROR = -9,
    REG_FIFO_DATA_READ_ERROR = -10,
    REG_FIFO_DATA_WRITE_ERROR = -11,
    REG_PART_ID_READ_ERROR = -12,
    PART_ID_ERROR = -13,
    REG_MODE_CONFIG_READ_ERROR = -14,
    REG_MODE_CONFIG_WRITE_ERROR = -15,
    REG_FIFO_CONFIG_READ_ERROR = -16,
    REG_FIFO_CONFIG_WRITE_ERROR = -17,
    REG_SPO2_CONFIG_READ_ERROR = -18,
    REG_SPO2_CONFIG_WRITE_ERROR = -19,
    REG_LED1_PA_READ_ERROR = -20,
    REG_LED1_PA_WRITE_ERROR = -21,
    REG_LED2_PA_READ_ERROR = -22,
    REG_LED2_PA_WRITE_ERROR = -23,
    REG_MULTI_LED_CTRL1_READ_ERROR = -24,
    REG_MULTI_LED_CTRL1_WRITE_ERROR = -25,
    REG_MULTI_LED_CTRL2_READ_ERROR = -26,
    REG_MULTI_LED_CTRL2_WRITE_ERROR = -27,
    REG_OVF_COUNTER_READ_ERROR = -28,
    REG_OVF_COUNTER_WRITE_ERROR = -29,
    REG_TEMP_CONFIG_READ_ERROR = -30,
    REG_TEMP_CONFIG_WRITE_ERROR = -31,
    REG_TEMP_INT_READ_ERROR = -32,
    REG_TEMP_INT_WRITE_ERROR = -33,
    REG_TEMP_FRAC_READ_ERROR = -34,
    REG_TEMP_FRAC_WRITE_ERROR = -35,
    REG_INT_STATUS1_READ_ERROR = -36,
    REG_INT_STATUS1_WRITE_ERROR = -37,
    REG_INT_STATUS2_READ_ERROR = -38,
    REG_INT_STATUS2_WRITE_ERROR = -39,
    REG_INT_ENABLE1_SETBITS_ERROR = -40,
    REG_INT_ENABLE1_CLRBITS_ERROR = -41,
    REG_INT_ENABLE2_SETBITS_ERROR = -42,
    REG_INT_ENABLE2_CLRBITS_ERROR = -43,
    NULL_PTR_ERROR = -44,
    MAX30102_RESET_ERROR = -45,
    MAX30102_WRITE_CLR_BITS_ERROR = -46,
    MAX30102_READ_CLR_BITS_ERROR = -47,
    MAX30102_WRITE_SET_BITS_ERROR = -48,
    MAX30102_READ_SET_BITS_ERROR = -49,
    FILEOPENERROR = -50,
    REG_ENABLE_ALL_INTERRUPT_ERROR = -51,
    MAX30102_GET_INTERRUPT_SRC_ERROR = -52,
    I2C_READ_TIMEOUT = -53,
    I2C_WRITE_TIMEOUT = -54,
} TerminateError;

const char *getErrStr(int err);
void terminate(int); 
#endif
